### ISSUE TITLE
Update alien Scheldt checklist 2024

### ISSUE THREAD

**Issue by sannegovaert** [trias-project/alien-scheldt-checklist#12]
We will release a new publication. I moved the data from the [old spreadsheet](https://docs.google.com/spreadsheets/d/1V_rQhyz_AjszobCMxBe-xFWI3kUNLrYzMeqyUNt3Vc4/edit?gid=0#gid=0) to the new big spreadsheet with all checklists together, so it is easier to manage.  Can you check wether the [current checklist](https://docs.google.com/spreadsheets/d/1LeXXbry2ArK2rngsmFjz_xErwE1KwQ8ujtvHNmTVA6E/edit?gid=541627250#gid=541627250) is up to date? 

Most important is to check:
- [ ] In the old checklist, there are some comments. Check if these are still relevant and if yes, make changes in the new spreadsheet.
- [ ] Add the species that were introduced since the last publication.
- [ ] There is missing data. Please fill in as much as possible, especially for `introduction pathway`, `date first observation` , `date last observation` and `native range`. 
When `date first observation` is missing, this species cannot be used in the [checklist indicator of TrIAS](https://trias-project.github.io/indicators/02_indicator_introductions_per_year.html).
- [ ] Make sure all data is correct/updated.
- [ ] Be aware that `occurence status` is statement about the presence or absence of a Taxon within the country between the date of first observation and last date of observation. Boccardiella hamata is marked as absent, but no observation dates are provided. So this line is meaningless. It is better to set the status on present and provide `last observation date`. If `last observation date` is not the current year, it is thus currently absent.
- [ ] The [vocabulary](https://rs.gbif.org/vocabulary/dwc/pathway_2022-02-02.xml) for `introduction pathway` has been updated. So we need to use the new terms. Please check if my suggestions are correct or need to be updated. In the spreadsheet, there is a tab `introduction pathway` with the short explanations of each term.  For a more thorough description, please check  the [CBD guidance for interpretation](https://op.europa.eu/en/publication-detail/-/publication/f8627bbc-1f15-11eb-b57e-01aa75ed71a1). It also provides examples and decision trees. Here is the overview:

old pathway | new proposed pathway | comments
-------------- | -------------- | ---------
stowaway_hull_fouling | hullFouling | 
stowaway_ballast_water | ballastWater | 
escape_aquaculture | aquacultureMariculture | 
pet | pet | 
stowaway  | otherTransport | Or choose one of the other options in the category transportStowaway
corridor_water | waterwaysBasinsSeas | 
contaminant_on_plants | contaminantOnPlants
release_fishery | fisheryInTheWild
stowayway_ship | hitchhikersShip
